title: aVenture Documentation
description: Documentation for aVenture, a private venture capital research platform
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aventurevc.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom SASS
sass:
  sass_dir: _sass
  style: compressed

# Explicitly set permalink style
permalink: /:title.html

# Default layout for pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Add this line to help with cache busting
version: 1.0.0
