remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: aVenture Documentation
description: Documentation for the aVenture VC research database
logo: /images/logos/aventure_logo_1280x640_transparent.png
show_downloads: false

# Theme-specific settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# GitHub metadata
github:
  is_project_page: false

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
